# Generated by Django 3.2 on 2021-06-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='linkdein_url',
        ),
    ]
